### PR TITLE
Add `.als` file support

### PR DESCRIPTION
**Pull request by omnv**
Closes https://github.com/phiresky/ripgrep-all/issues/184.

### CODE REVIEW

**Review by lafrenierejm — APPROVED** [review]

**Comment by phiresky** [comment]
@lafrenierejm

```
pre-commit-run> nixfmt...................................................................Passed
pre-commit-run> rustfmt..................................................................Passed
pre-commit-run> typos....................................................................Failed
pre-commit-run> - hook id: typos
pre-commit-run> - exit code: 2
pre-commit-run> error: `als` should be `also`
pre-commit-run>   --> src/adapters/decompress.rs:11:33
pre-commit-run>    |
pre-commit-run> 11 | static EXTENSIONS: &[&str] = &["als", "bz2", "gz", "tbz", "tbz2", "tgz", "xz", "zst"];
pre-commit-run>    |                                 ^^^
pre-commit-run>    |
pre-commit-run> error: `als` should be `also`
pre-commit-run>   --> src/adapters/decompress.rs:65:14
pre-commit-run>    |
pre-commit-run> 65 |             "als" | "gz" | "tgz" => gz(inp),
pre-commit-run>    |              ^^^
pre-commit-run>    |
```

please disable spell checking?

**Comment by lafrenierejm** [comment]
> please disable spell checking?

I have raised https://github.com/omnv/ripgrep-all/pull/1 against @omnv's branch to fix the CI error.

**Comment by phiresky** [comment]
@lafrenierejm I'm not really convinced that spell checking string literals is more useful than it is annoying but sure I guess

**Comment by lafrenierejm** [comment]
> @lafrenierejm I'm not really convinced that spell checking string literals is more useful than it is annoying but sure I guess

@phiresky We can definitely remove `typos` from list of pre-commit and CI checks if you'd like. I also opened https://github.com/crate-ci/typos/issues/832 just now; if that issue gets traction then we might be able to continue using `typos` but with a lower rate of false-positives. I am fine either way, so just LMK if you'd prefer to remove `typos` entirely!

**Pull request merged**
