### PR TITLE
Fix installation and CI

### PR DESCRIPTION
**Pull request by TriplEight**
- Fixes installation with the stable toolchain.
  Essentially it's just `cargo update`
- Fixes the push pipeline, now it fails on a test
- Fixes the release pipeline

### CODE REVIEW

**Comment by TriplEight** [comment]
Had to get rid of msvc test and windows altogether because didn't decide how to install `poppler` there.

**Comment by phiresky** [comment]
Why does the CI need to have poppler at all?

**Comment by TriplEight** [comment]
> Why does the CI need to have poppler at all?

Because otherwise, CI will fail the [test](https://github.com/TriplEight/ripgrep-all/blob/baca166fdab3d2466ac9c482c3c9b8e160014b9a/src/adapters/custom.rs#L223) which relies on `pdftotext` binary.
If there's a Rust implementation of `pdftotext` it would be a way better to use that one mentioning it in the dependencies.

**Comment by TriplEight** [comment]
`win-msvc` test fails with https://github.com/phiresky/ripgrep-all/runs/1621230957#step:11:241
`win-gnu` build fails with https://github.com/phiresky/ripgrep-all/pull/92/checks?check_run_id=1625639166#step:9:566

I'm removing windows CI steps to make this PR mergeable and address the issues later.

**Comment by TriplEight** [comment]
@phiresky anything you want to add before merging?

**Comment by phiresky** [comment]
It's fine if we don't run the tests on Windows, but we do need the windows build in CI

**Comment by jounathaen** [comment]
I'd like to give this a little bump, as this one prevents me from installing rga via cargo :slightly_smiling_face:

**Comment by TriplEight** [comment]
@phiresky there are no changes to release, it's just fixed

**Pull request merged**
